"""Curated well-known Israeli family places, used alongside Google Places results."""

CITY_COORDS = {
    "tel aviv": (32.0853, 34.7818),
    "jerusalem": (31.7683, 35.2137),
    "haifa": (32.7940, 34.9896),
    "eilat": (29.5577, 34.9519),
    "beer sheva": (31.2518, 34.7913),
    "netanya": (32.3215, 34.8532),
    "raanana": (32.1848, 34.8713),
    "herzliya": (32.1624, 34.8447),
    "rishon": (31.9730, 34.7925),
    "ramat gan": (32.0684, 34.8248),
    "tiberias": (32.7959, 35.5312),
    "nazareth": (32.6996, 35.3035),
    "ashdod": (31.8040, 34.6553),
    "modiin": (31.8928, 35.0104),
    "petah tikva": (32.0871, 34.8878),
}

# Image pools
IMG = {
    "park1": "https://images.unsplash.com/photo-1634608874538-443b84f7b06b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODB8MHwxfHNlYXJjaHw0fHxraWRzJTIwcGxheWdyb3VuZCUyMHBhcmslMjBmYW1pbHklMjBhY3Rpdml0eXxlbnwwfHx8fDE3ODg3OTYyNDB8MA&ixlib=rb-4.1.0&q=85",
    "park2": "https://images.unsplash.com/photo-1591865527703-ce63c96b984f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODB8MHwxfHNlYXJjaHwyfHxraWRzJTIwcGxheWdyb3VuZCUyMHBhcmslMjBmYW1pbHklMjBhY3Rpdml0eXxlbnwwfHx8fDE3ODg3OTYyNDB8MA&ixlib=rb-4.1.0&q=85",
    "park3": "https://images.unsplash.com/photo-1575783970733-1aaedde1db74?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODB8MHwxfHNlYXJjaHwxfHxraWRzJTIwcGxheWdyb3VuZCUyMHBhcmslMjBmYW1pbHklMjBhY3Rpdml0eXxlbnwwfHx8fDE3ODg3OTYyNDB8MA&ixlib=rb-4.1.0&q=85",
    "beach1": "https://images.unsplash.com/photo-1597524678053-5e6fef52d8a3?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2OTV8MHwxfHNlYXJjaHwzfHxmYW1pbHklMjBiZWFjaCUyMHN1bm55fGVufDB8fHx8MTc4NzA4ODI2NXww&ixlib=rb-4.1.0&q=85",
    "beach2": "https://images.unsplash.com/photo-1721840432289-d0041522103d?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2OTV8MHwxfHNlYXJjaHw0fHxmYW1pbHklMjBiZWFjaCUyMHN1bm55fGVufDB8fHx8MTc4NzA4ODI2NXww&ixlib=rb-4.1.0&q=85",
    "museum1": "https://images.unsplash.com/photo-1768154576965-61e5776268a7?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NzF8MHwxfHNlYXJjaHwyfHxjaGlsZHJlbiUyMHNjaWVuY2UlMjBtdXNldW0lMjBpbmRvb3IlMjBhY3Rpdml0eXxlbnwwfHx8fDE3ODg3OTYyNDl8MA&ixlib=rb-4.1.0&q=85",
    "zoo1": "https://images.unsplash.com/photo-1503918756811-975bd3397178?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMzl8MHwxfHNlYXJjaHwyfHxjaGlsZHJlbiUyMHpvbyUyMGFuaW1hbHMlMjBmYW1pbHl8ZW58MHx8fHwxNzg4ODAwNjM1fDA&ixlib=rb-4.1.0&q=85",
    "zoo2": "https://images.unsplash.com/photo-1503919005314-30d93d07d823?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMzl8MHwxfHNlYXJjaHwxfHxjaGlsZHJlbiUyMHpvbyUyMGFuaW1hbHMlMjBmYW1pbHl8ZW58MHx8fHwxNzg4ODAwNjM1fDA&ixlib=rb-4.1.0&q=85",
    "zoo3": "https://images.unsplash.com/photo-1635150949018-ca33f7cddc85?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjAzMzl8MHwxfHNlYXJjaHwzfHxjaGlsZHJlbiUyMHpvbyUyMGFuaW1hbHMlMjBmYW1pbHl8ZW58MHx8fHwxNzg4ODAwNjM1fDA&ixlib=rb-4.1.0&q=85",
    "indoor1": "https://images.unsplash.com/photo-1760704892974-60b5ddb59825?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzV8MHwxfHNlYXJjaHwyfHxpbmRvb3IlMjBwbGF5Z3JvdW5kJTIwa2lkcyUyMHBsYXklMjBhcmVhfGVufDB8fHx8MTc4ODgwMDYzNXww&ixlib=rb-4.1.0&q=85",
    "indoor2": "https://images.unsplash.com/photo-1759330203240-b89ccee8840f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjY2NzV8MHwxfHNlYXJjaHwxfHxpbmRvb3IlMjBwbGF5Z3JvdW5kJTIwa2lkcyUyMHBsYXklMjBhcmVhfGVufDB8fHx8MTc4ODgwMDYzNXww&ixlib=rb-4.1.0&q=85",
    "aqua1": "https://images.unsplash.com/photo-1583949184685-33fda190a216?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2OTV8MHwxfHNlYXJjaHwxfHxhcXVhcml1bSUyMGZpc2glMjB0YW5rJTIwY2hpbGRyZW58ZW58MHx8fHwxNzg4ODAwNjM1fDA&ixlib=rb-4.1.0&q=85",
    "aqua2": "https://images.unsplash.com/photo-1543332143-4e8c27e3256f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2OTV8MHwxfHNlYXJjaHwyfHxhcXVhcml1bSUyMGZpc2glMjB0YW5rJTIwY2hpbGRyZW58ZW58MHx8fHwxNzg4ODAwNjM1fDA&ixlib=rb-4.1.0&q=85",
    "water1": "https://images.unsplash.com/photo-1706843540890-a4249dad97b6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NzR8MHwxfHNlYXJjaHwxfHx3YXRlciUyMHBhcmslMjBzbGlkZXMlMjBmYW1pbHklMjBmdW58ZW58MHx8fHwxNzg4ODAwNjM1fDA&ixlib=rb-4.1.0&q=85",
    "water2": "https://images.unsplash.com/photo-1706843540922-5682f3ad5b98?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NzR8MHwxfHNlYXJjaHwyfHx3YXRlciUyMHBhcmslMjBzbGlkZXMlMjBmYW1pbHklMjBmdW58ZW58MHx8fHwxNzg4ODAwNjM1fDA&ixlib=rb-4.1.0&q=85",
    "amuse1": "https://images.unsplash.com/photo-1577774438656-768f1e5d9ed6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NzB8MHwxfHNlYXJjaHwxfHxhbXVzZW1lbnQlMjBwYXJrJTIwcmlkZXMlMjBjYXJvdXNlbHxlbnwwfHx8fDE3ODg4MDA2MzV8MA&ixlib=rb-4.1.0&q=85",
    "amuse2": "https://images.unsplash.com/photo-1542332606-b2d1c52a6c33?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NzB8MHwxfHNlYXJjaHwyfHxhbXVzZW1lbnQlMjBwYXJrJTIwcmlkZXMlMjBjYXJvdXNlbHxlbnwwfHx8fDE3ODg4MDA2MzV8MA&ixlib=rb-4.1.0&q=85",
    "event1": "https://images.unsplash.com/photo-1663223271802-b3b71fa1b77b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODF8MHwxfHNlYXJjaHwzfHxwdXBwZXQlMjBzaG93JTIwdGhlYXRlciUyMGtpZHMlMjBldmVudHxlbnwwfHx8fDE3ODg4MDA2MzV8MA&ixlib=rb-4.1.0&q=85",
    "event2": "https://images.unsplash.com/photo-1605980045919-4abfbb1c3260?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODF8MHwxfHNlYXJjaHwyfHxwdXBwZXQlMjBzaG93JTIwdGhlYXRlciUyMGtpZHMlMjBldmVudHxlbnwwfHx8fDE3ODg4MDA2MzV8MA&ixlib=rb-4.1.0&q=85",
    "event3": "https://images.unsplash.com/photo-1432639020363-5632f7f04e0b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1ODF8MHwxfHNlYXJjaHwxfHxwdXBwZXQlMjBzaG93JTIwdGhlYXRlciUyMGtpZHMlMjBldmVudHxlbnwwfHx8fDE3ODg4MDA2MzV8MA&ixlib=rb-4.1.0&q=85",
}

ALL_AGES = ["0-2", "3-5", "6-9", "10+"]

ACTIVITIES = [
    # --- Tel Aviv area ---
    {"id": "a1", "name": "Park HaYarkon Playground", "category": "park", "address": "Rokach Blvd, Tel Aviv", "city": "Tel Aviv",
     "lat": 32.1020, "lng": 34.8040, "rating": None, "reviews": 0, "image": IMG["park1"],
     "description": "Tel Aviv's biggest green lung with huge playgrounds, boating lake, bike paths and open lawns for picnics.",
     "ages": ALL_AGES, "setting": "outdoor", "price": "free", "hours": None,
     "features": ["stroller_friendly", "parking", "picnic", "toilets"]},
    {"id": "a2", "name": "Meymadion Water Park", "category": "water_park", "address": "Ganei Yehoshua, Tel Aviv", "city": "Tel Aviv",
     "lat": 32.1075, "lng": 34.8168, "rating": None, "reviews": 0, "image": IMG["water1"],
     "description": "Israel's largest water park with wave pools, kid lagoons and dozens of slides. Summer season only.",
     "ages": ["3-5", "6-9", "10+"], "setting": "outdoor", "price": "paid", "hours": None,
     "features": ["parking", "food", "lockers"]},
    {"id": "a5", "name": "Luna Park Tel Aviv", "category": "amusement_park", "address": "Ganei Yehoshua, Tel Aviv", "city": "Tel Aviv",
     "lat": 32.1090, "lng": 34.8130, "rating": None, "reviews": 0, "image": IMG["amuse1"],
     "description": "Classic amusement park with roller coasters, carousels and gentle rides for little ones.",
     "ages": ["3-5", "6-9", "10+"], "setting": "outdoor", "price": "paid", "hours": None,
     "features": ["parking", "food", "toddler_rides"]},

    # --- Jerusalem ---
    {"id": "a6", "name": "Bloomfield Science Museum", "category": "museum", "address": "Hebrew University, Jerusalem", "city": "Jerusalem",
     "lat": 31.7920, "lng": 35.2010, "rating": None, "reviews": 0, "image": IMG["museum1"],
     "description": "Hands-on interactive science exhibits kids can touch, push and experiment with. Endless curiosity.",
     "ages": ["3-5", "6-9", "10+"], "setting": "indoor", "price": "paid", "hours": None,
     "features": ["air_conditioned", "parking", "gift_shop", "workshops"]},
    {"id": "a7", "name": "Jerusalem Biblical Zoo", "category": "zoo", "address": "Malha, Jerusalem", "city": "Jerusalem",
     "lat": 31.7460, "lng": 35.1830, "rating": None, "reviews": 0, "image": IMG["zoo1"],
     "description": "Beautiful hillside zoo with a petting corner, monkeys and a wooden Noah's Ark visitor center.",
     "ages": ALL_AGES, "setting": "outdoor", "price": "paid", "hours": None,
     "features": ["stroller_friendly", "parking", "petting_zoo", "food"]},
    {"id": "a8", "name": "Gan Sacher (Sacher Park)", "category": "park", "address": "Sacher Park, Jerusalem", "city": "Jerusalem",
     "lat": 31.7830, "lng": 35.2050, "rating": None, "reviews": 0, "image": IMG["park2"],
     "description": "Jerusalem's largest park with vast lawns, shaded playgrounds and space to run and fly kites.",
     "ages": ALL_AGES, "setting": "outdoor", "price": "free", "hours": None,
     "features": ["parking", "picnic", "toilets", "shade"]},

    # --- Haifa & North ---
    {"id": "a10", "name": "MadaTech Science Museum", "category": "museum", "address": "Old Technion, Haifa", "city": "Haifa",
     "lat": 32.7940, "lng": 34.9896, "rating": None, "reviews": 0, "image": IMG["museum1"],
     "description": "Israel's national science & technology museum with huge interactive halls and a science park outside.",
     "ages": ["3-5", "6-9", "10+"], "setting": "indoor", "price": "paid", "hours": None,
     "features": ["air_conditioned", "parking", "outdoor_park", "workshops"]},
    {"id": "a11", "name": "Haifa Educational Zoo", "category": "zoo", "address": "Gan HaEm, Haifa", "city": "Haifa",
     "lat": 32.8050, "lng": 34.9880, "rating": None, "reviews": 0, "image": IMG["zoo2"],
     "description": "Compact green zoo on Mount Carmel with a prehistory museum and a lovely park nearby.",
     "ages": ALL_AGES, "setting": "outdoor", "price": "paid", "hours": None,
     "features": ["stroller_friendly", "parking", "petting_zoo"]},
    {"id": "a12", "name": "Hof HaCarmel Beach", "category": "beach", "address": "Carmel Beach, Haifa", "city": "Haifa",
     "lat": 32.8340, "lng": 34.9560, "rating": None, "reviews": 0, "image": IMG["beach2"],
     "description": "Wide sandy family beach with gentle waves, lifeguards, and plenty of parking.",
     "ages": ALL_AGES, "setting": "outdoor", "price": "free", "hours": None,
     "features": ["lifeguard", "parking", "showers", "food"]},

    # --- Sharon / Center ---
    {"id": "a13", "name": "Raanana Park", "category": "park", "address": "Ahuza St, Raanana", "city": "Raanana",
     "lat": 32.1848, "lng": 34.8713, "rating": None, "reviews": 0, "image": IMG["park3"],
     "description": "Family favourite with a boating lake, mini train, huge shaded playgrounds and a petting corner.",
     "ages": ALL_AGES, "setting": "outdoor", "price": "free", "hours": None,
     "features": ["stroller_friendly", "parking", "mini_train", "petting_zoo", "food"]},
    {"id": "a14", "name": "SuperLand Amusement Park", "category": "amusement_park", "address": "Rishon LeZion", "city": "Rishon LeZion",
     "lat": 31.9730, "lng": 34.7925, "rating": None, "reviews": 0, "image": IMG["amuse2"],
     "description": "Family theme park with rides for all ages, from a gentle toddler zone to bigger coasters.",
     "ages": ["3-5", "6-9", "10+"], "setting": "outdoor", "price": "paid", "hours": None,
     "features": ["parking", "food", "toddler_rides"]},
    {"id": "a15", "name": "Herzliya Marina Beach", "category": "beach", "address": "Herzliya Pituach", "city": "Herzliya",
     "lat": 32.1650, "lng": 34.7960, "rating": None, "reviews": 0, "image": IMG["beach1"],
     "description": "Sheltered marina beach with calm water, boardwalk cafes and ice-cream stops.",
     "ages": ALL_AGES, "setting": "outdoor", "price": "free", "hours": None,
     "features": ["lifeguard", "food", "boardwalk", "parking"]},

    # --- Eilat / South ---
    {"id": "a17", "name": "Coral World Underwater Observatory", "category": "aquarium", "address": "Coral Beach, Eilat", "city": "Eilat",
     "lat": 29.5080, "lng": 34.9200, "rating": None, "reviews": 0, "image": IMG["aqua1"],
     "description": "Marine park with an underwater observatory, shark pool and turtle tanks over the Red Sea reef.",
     "ages": ALL_AGES, "setting": "indoor", "price": "paid", "hours": None,
     "features": ["parking", "food", "gift_shop", "stroller_friendly"]},
    {"id": "a18", "name": "Dolphin Reef Eilat", "category": "aquarium", "address": "Southern Beach, Eilat", "city": "Eilat",
     "lat": 29.5150, "lng": 34.9250, "rating": None, "reviews": 0, "image": IMG["aqua2"],
     "description": "Watch dolphins in their natural bay, relax on floating pontoons and enjoy a shaded beach.",
     "ages": ["3-5", "6-9", "10+"], "setting": "outdoor", "price": "paid", "hours": None,
     "features": ["beach", "food", "parking"]},
    {"id": "a19", "name": "Ice Mall Eilat (ice rink)", "category": "indoor_play", "address": "Eilat", "city": "Eilat",
     "lat": 29.5577, "lng": 34.9519, "rating": None, "reviews": 0, "image": IMG["indoor2"],
     "description": "Indoor ice-skating rink and play area - a cool refuge from Eilat's desert heat.",
     "ages": ["6-9", "10+"], "setting": "indoor", "price": "paid", "hours": None,
     "features": ["air_conditioned", "skate_rental", "cafe"]},

    # --- Extra variety ---
    {"id": "a20", "name": "Safari Ramat Gan Zoo", "category": "zoo", "address": "Ramat Gan Safari", "city": "Ramat Gan",
     "lat": 32.0530, "lng": 34.8300, "rating": None, "reviews": 0, "image": IMG["zoo3"],
     "description": "Drive-through African safari plus a walking zoo - lions, elephants and monkeys up close.",
     "ages": ALL_AGES, "setting": "outdoor", "price": "paid", "hours": None,
     "features": ["parking", "drive_through", "food", "stroller_friendly"]},
]



